# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python-tcp',
                'doc_host': 'https://Matthew-Redrup.github.io',
                'git_url': 'https://github.com/Matthew-Redrup/python-tcp',
                'lib_path': 'python_tcp'},
  'syms': { 'python_tcp.core': { 'python_tcp.core.SocketState': ('core.html#socketstate', 'python_tcp/core.py'),
                                 'python_tcp.core.TCPConnection': ('core.html#tcpconnection', 'python_tcp/core.py'),
                                 'python_tcp.core.TCPConnection.__str__': ('core.html#tcpconnection.__str__', 'python_tcp/core.py'),
                                 'python_tcp.core.TCPConnection.update_state': ( 'core.html#tcpconnection.update_state',
                                                                                 'python_tcp/core.py'),
                                 'python_tcp.core.get_free_port': ('core.html#get_free_port', 'python_tcp/core.py')}}}
